// =============================================================================
// Scenario expansion: the `.par` implementation against a single combined query.
//
// A reviewer objected that the paper proposes, only vaguely discussed, an
// optimization that collapses multiple scenarios into one execution using
// Scala's `.par`, that this looks like multi-query optimization, that the author
// should have checked whether combining all the queries that produce multiple
// results into a single one gives the same result, and that as it stands it
// looks like a static implementation that only works for his case.
//
// Three implementations of the same transformation, so the objection can be
// answered with a measurement rather than an argument:
//
//   par   the published one (joinless_v5.tex:889-910): a mapPartitions pass that
//         expands each input row into one row per scenario, with the expansion
//         done through a Scala parallel collection.
//   seq   the same loop with `.par` removed. This isolates what `.par`
//         contributes, which the paper never established: the objection is about
//         whether the parallel collection is doing anything, and neither `par`
//         alone nor `par` against a SQL plan answers that.
//   sql   the single combined query the reviewer asks for. An unpivot of N
//         scenario column-groups into N rows is expressed as one `explode` over
//         an array of structs — the relational equivalent, planned and
//         code-generated by Spark rather than executed row-by-row in Scala.
//
// All three must produce identical output. Equivalence is checked per scenario,
// not only in aggregate, because an unpivot that mixed up which scenario a row
// belonged to would still balance in total.
//
// On the "static implementation" part of the objection: `par` and `seq` read
// their columns by interpolated name inside the row loop, so the set of
// scenarios is fixed at compile time in the shape of the code. `sql` builds its
// array of structs from a list, so a different scenario set is a different
// argument rather than a different program. That difference is structural and is
// reported alongside the times.
//
// Usage: ./scripts/jpp ScenarioUnpivot <dataDir> <par|seq|sql> [csvOut]
// =============================================================================

import org.apache.spark.sql._
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions._
import java.io.{File, PrintWriter}
import scala.collection.mutable

object ScenarioUnpivot {

  final val N_SCENARIOS = 3

  private val outputSchema = StructType(Seq(
    StructField("ENTITY_ID",         StringType, nullable = true),
    StructField("INSTRUMENT_ID",     StringType, nullable = true),
    StructField("VALUATION_METHOD",  StringType, nullable = true),
    StructField("PROTECTION_METHOD", StringType, nullable = true),
    StructField("COUNTERPARTY_EXPOSURE", DoubleType, nullable = true),
    StructField("SCENARIO",          IntegerType, nullable = false)
  ))

  /** The published implementation. Kept as close to the listing as the
    * surrounding code allows: the parallel collection, the per-row buffer, and
    * the column access by interpolated name are all as printed. */
  def viaPar(df: DataFrame, n: Int = N_SCENARIOS): DataFrame = {
    val spark = df.sparkSession
    val scenarios = (1 to n).toList
    val rdd = df.rdd.mapPartitions { iter =>
      val buffer = mutable.ArrayBuffer[Row]()
      iter.foreach { row =>
        val entityId     = row.getAs[String]("ENTITY_ID")
        val instrumentId = row.getAs[String]("INSTRUMENT_ID")
        val scenarioResults = scenarios.par.map { i =>
          val valuationMethod  = row.getAs[String](s"VALUATION_METHOD_SC_$i")
          val protectionMethod = row.getAs[String](s"PROTECTION_METHOD_SC_$i")
          val counterpartyExp  = row.getAs[Double](s"COUNTERPARTY_EXPOSURE_SC$i")
          Row(entityId, instrumentId, valuationMethod, protectionMethod, counterpartyExp, i)
        }
        buffer ++= scenarioResults.seq
      }
      buffer.iterator
    }
    spark.createDataFrame(rdd, outputSchema)
  }

  /** The same loop without the parallel collection. */
  def viaSeq(df: DataFrame, n: Int = N_SCENARIOS): DataFrame = {
    val spark = df.sparkSession
    val scenarios = (1 to n).toList
    val rdd = df.rdd.mapPartitions { iter =>
      val buffer = mutable.ArrayBuffer[Row]()
      iter.foreach { row =>
        val entityId     = row.getAs[String]("ENTITY_ID")
        val instrumentId = row.getAs[String]("INSTRUMENT_ID")
        scenarios.foreach { i =>
          val valuationMethod  = row.getAs[String](s"VALUATION_METHOD_SC_$i")
          val protectionMethod = row.getAs[String](s"PROTECTION_METHOD_SC_$i")
          val counterpartyExp  = row.getAs[Double](s"COUNTERPARTY_EXPOSURE_SC$i")
          buffer += Row(entityId, instrumentId, valuationMethod, protectionMethod, counterpartyExp, i)
        }
      }
      buffer.iterator
    }
    spark.createDataFrame(rdd, outputSchema)
  }

  /** The single combined query. One `explode` over an array of per-scenario
    * structs: no RDD, no row-by-row Scala, and the scenario list is data. */
  def viaSql(df: DataFrame, n: Int = N_SCENARIOS): DataFrame = {
    val perScenario = (1 to n).map { i =>
      struct(
        col(s"VALUATION_METHOD_SC_$i").alias("VALUATION_METHOD"),
        col(s"PROTECTION_METHOD_SC_$i").alias("PROTECTION_METHOD"),
        col(s"COUNTERPARTY_EXPOSURE_SC$i").alias("COUNTERPARTY_EXPOSURE"),
        lit(i).alias("SCENARIO"))
    }
    df.select(col("ENTITY_ID"), col("INSTRUMENT_ID"),
              explode(array(perScenario: _*)).alias("s"))
      .select(col("ENTITY_ID"), col("INSTRUMENT_ID"),
              col("s.VALUATION_METHOD"), col("s.PROTECTION_METHOD"),
              col("s.COUNTERPARTY_EXPOSURE"), col("s.SCENARIO"))
  }

  def build(df: DataFrame, variant: String, n: Int = N_SCENARIOS): DataFrame = variant match {
    case "par" => viaPar(df, n)
    case "seq" => viaSeq(df, n)
    case "sql" => viaSql(df, n)
    case other => throw new IllegalArgumentException(s"unknown variant: $other")
  }

  def main(args: Array[String]): Unit = {
    val dataDir = if (args.nonEmpty)   args(0) else "/home/athenas/ssb_scenarios"
    val variant = if (args.length > 1) args(1) else "par"
    val csvOut  = if (args.length > 2) args(2) else "results/multiquery.csv"
    val cores   = if (args.length > 3) args(3) else "16"

    val spark = SparkSession.builder()
      .appName(s"ScenarioUnpivot-$variant")
      .master(sys.env.getOrElse("SPARK_MASTER", s"local[$cores]"))
      .config("spark.sql.adaptive.enabled", "false")
      .getOrCreate()

    RunReport.install(spark, sys.env.getOrElse("JPP_RUN_LABEL", s"unpivot-$variant"))

    val src = spark.read.parquet(s"$dataDir/scenarios")
    PartitionGuard.check(Seq("scenarios" -> src), s"ScenarioUnpivot/$variant")

    val t0 = System.nanoTime()
    val out = build(src, variant).cache()

    // Per-scenario signature, not just a total. An unpivot that attached rows to
    // the wrong scenario would still produce the right overall sum, so the check
    // has to be per scenario to mean anything.
    val perScenario = out.groupBy("SCENARIO")
      .agg(count(lit(1)).alias("n"),
           sum("COUNTERPARTY_EXPOSURE").alias("exposure"),
           countDistinct("VALUATION_METHOD").alias("valuations"),
           countDistinct("PROTECTION_METHOD").alias("protections"))
      .orderBy("SCENARIO")
      .collect()

    val rows = out.count()
    val elapsed = (System.nanoTime() - t0) / 1e9

    println(f"variant       = $variant")
    println(f"rows out      = $rows")
    println(f"elapsed       = $elapsed%.2f s")
    perScenario.foreach { r =>
      println(f"  scenario ${r.getInt(0)}: n=${r.getLong(1)}%,12d  " +
              f"exposure=${r.getDouble(2)}%,20.2f  " +
              f"valuations=${r.getLong(3)}  protections=${r.getLong(4)}")
    }

    new File(csvOut).getAbsoluteFile.getParentFile.mkdirs()
    val exists = new File(csvOut).exists()
    val w = new PrintWriter(new java.io.FileWriter(csvOut, true))
    try {
      if (!exists) w.println("variant,scenario,rows_out,n,exposure,valuations,protections,elapsed_s")
      def d(x: Double, p: Int) = String.format(java.util.Locale.ROOT, s"%.${p}f", Double.box(x))
      perScenario.foreach { r =>
        w.println(s"$variant,${r.getInt(0)},$rows,${r.getLong(1)},${d(r.getDouble(2), 2)}," +
                  s"${r.getLong(3)},${r.getLong(4)},${d(elapsed, 3)}")
      }
    } finally w.close()

    RunReport.emit(spark)
    out.unpersist()
    spark.stop()
  }
}
